package org.jellyfin.mobile.model

enum class BaseItemKind(val serialName: String) {
    AggregateFolder("AggregateFolder"),
    Audio("Audio"),
    AudioBook("AudioBook"),
    BasePluginFolder("BasePluginFolder"),
    Book("Book"),
    BoxSet("BoxSet"),
    Channel("Channel"),
    ChannelFolderItem("ChannelFolderItem"),
    CollectionFolder("CollectionFolder"),
    Episode("Episode"),
    Folder("Folder"),
    Genre("Genre"),
    ManualPlaylistsFolder("ManualPlaylistsFolder"),
    Movie("Movie"),
    MusicAlbum("MusicAlbum"),
    MusicArtist("MusicArtist"),
    MusicGenre("MusicGenre"),
    MusicVideo("MusicVideo"),
    Person("Person"),
    Photo("Photo"),
    PhotoAlbum("PhotoAlbum"),
    Playlist("Playlist"),
    Program("Program"),
    Recording("Recording"),
    Season("Season"),
    Series("Series"),
    Studio("Studio"),
    Trailer("Trailer"),
    TvChannel("TvChannel"),
    TvProgram("TvProgram"),
    UserRootFolder("UserRootFolder"),
    UserView("UserView"),
    Video("Video"),
    Year("Year"),
}
