name: App / Lint

on:
  push:
    branches:
      - master
      - release-*
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      matrix:
        task: [ detekt, lint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Setup Java
        uses: actions/setup-java@b36c23c0d998641eff861008f374ee103c25ac73 # v4.4.0
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
      - name: Run ${{ matrix.task }} task
        run: ./gradlew ${{ matrix.task }}
      - name: Upload SARIF files
        uses: github/codeql-action/upload-sarif@c36620d31ac7c881962c3d9dd939c40ec9434f2b # v3.26.12
        if: ${{ always() }}
        with:
          sarif_file: .
