name: Gradle / Validate wrapper

on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - '**/gradlе-wrapper.jar'

permissions:
  contents: read

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0
